version: '3'
services:
  dbserver:
    build: mysql
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=bs2g
    ports:
      - "3306:3306"
    hostname: dbserver
  nodeapp:
    build: node
    container_name: node
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "3000:3000"
    links:
      - dbserver
    command: node app.js
  webserver:
    build: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "8080:8080"
    links:
      - 'nodeapp'